# Generated by Django 4.2.17 on 2024-12-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarwindow',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
