# Generated by Django 4.2.17 on 2024-12-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_calendarwindow_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarwindow',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
