# Generated by Django 4.2.17 on 2024-12-18 11:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_rating_user_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarwindow',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
